name: NuGet Publish

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build and Test
      run: dotnet test --verbosity normal
    - name: Build release
      run: dotnet build -c Release
    - name: Publish GitHub
      run: |
        dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUBTOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DrEsteban/index.json"
        dotnet nuget push --skip-duplicate --api-key ${{ secrets.GITHUBTOKEN }} ./**/Release/*.nupkg --source github
    - name: Publish NuGet
      run: dotnet nuget push --skip-duplicate --api-key ${{ secrets.NUGETTOKEN }} ./**/Release/*.nupkg --source https://api.nuget.org/v3/index.json
