name: NuGet Publish

on: { }

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build and Test
      run: dotnet test --verbosity normal
    - name: Pack
      run: dotnet pack
    - name: Publish
      run: dotnet nuget push --api-key ${{ secrets.NUGETTOKEN }}
